# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:/project/DeepFrag/DeepFrag.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 360, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.SmiInput = QtWidgets.QTextEdit(self.centralwidget)
        self.SmiInput.setGeometry(QtCore.QRect(170, 280, 201, 41))
        self.SmiInput.setObjectName("SmiInput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 280, 131, 41))
        self.label.setObjectName("label")
        self.MolView = QtWidgets.QLabel(self.centralwidget)
        self.MolView.setGeometry(QtCore.QRect(450, 100, 256, 192))
        self.MolView.setObjectName("MolView")
        self.EgyInput = QtWidgets.QComboBox(self.centralwidget)
        self.EgyInput.setGeometry(QtCore.QRect(210, 230, 87, 22))
        self.EgyInput.setObjectName("EgyInput")
        self.EgyInput.addItem("")
        self.EgyInput.addItem("")
        self.EgyInput.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 230, 141, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 141, 21))
        self.label_3.setObjectName("label_3")
        self.ModInput = QtWidgets.QComboBox(self.centralwidget)
        self.ModInput.setGeometry(QtCore.QRect(210, 170, 101, 21))
        self.ModInput.setObjectName("ModInput")
        self.ModInput.addItem("")
        self.ModInput.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 50, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(450, 340, 481, 321))
        self.groupBox.setObjectName("groupBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.label.setText(_translate("MainWindow", "Input SMILES:"))
        self.EgyInput.setItemText(0, _translate("MainWindow", "10 eV"))
        self.EgyInput.setItemText(1, _translate("MainWindow", "30 eV"))
        self.EgyInput.setItemText(2, _translate("MainWindow", "50 eV"))
        self.label_2.setText(_translate("MainWindow", "Collision Energy:"))
        self.label_3.setText(_translate("MainWindow", "Ion Mode:"))
        self.ModInput.setItemText(0, _translate("MainWindow", "Positive"))
        self.ModInput.setItemText(1, _translate("MainWindow", "Negative"))
        self.label_4.setText(_translate("MainWindow", "DeepFrag"))
        self.groupBox.setTitle(_translate("MainWindow", ""))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

